# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea74d9704e537b20313dce84209c9512309375a6fcbb69299347247506fd5ff6f271f604062319f187e2c5a4b1ab77a7dd143449ea9de9f12284a8a4115df7d3

test:
  secret_key_base: e6b109918e0ed139d13251fc0aa6ab870762369981db84722cb5eecbfde7bbb0270fb5a8761d734e214d30a7c22720e812860a39eee6f8f4d977b359f397a87b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
